@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteAssignmentCommandParser" as DeleteAssignmentCommandParser LOGIC_COLOR
participant "d:DeleteAssignmentCommand" as DeleteAssignmentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete-a 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete-a 1")
activate AddressBookParser

create DeleteAssignmentCommandParser
AddressBookParser -> DeleteAssignmentCommandParser
activate DeleteAssignmentCommandParser

DeleteAssignmentCommandParser --> AddressBookParser
deactivate DeleteAssignmentCommandParser

AddressBookParser -> DeleteAssignmentCommandParser : parse("1")
activate DeleteAssignmentCommandParser

create DeleteAssignmentCommand
DeleteAssignmentCommandParser -> DeleteAssignmentCommand
activate DeleteAssignmentCommand

DeleteAssignmentCommand --> DeleteAssignmentCommandParser : d
deactivate DeleteAssignmentCommand

DeleteAssignmentCommandParser --> AddressBookParser : d
deactivate DeleteAssignmentCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteAssignmentCommandParser -[hidden]-> AddressBookParser
destroy DeleteAssignmentCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteAssignmentCommand : execute()
activate DeleteAssignmentCommand

DeleteAssignmentCommand -> Model : deleteAssignment(1)
activate Model

Model --> DeleteAssignmentCommand
deactivate Model

create CommandResult
DeleteAssignmentCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteAssignmentCommand
deactivate CommandResult

DeleteAssignmentCommand --> LogicManager : result
deactivate DeleteAssignmentCommand

[<--LogicManager
deactivate LogicManager
@enduml
